package br.com.model;

// Generated 03/09/2012 17:07:48 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Contasareceber generated by hbm2java
 */
@Entity
@Table(name = "contasareceber", catalog = "geven")
public class Contasareceber implements java.io.Serializable {

	private Integer codigo;
	private int unidade;
	private Integer cliente;
	private Date mesreferencia;
	private String tipodoc;
	private Integer venda;
	private double valor;
	private Date datavencimento;
	private int parcela;
	private int dia;
	private Set parcelasarecebers = new HashSet(0);

	public Contasareceber() {
	}

	public Contasareceber(int unidade, double valor, Date datavencimento,
			int parcela, int dia) {
		this.unidade = unidade;
		this.valor = valor;
		this.datavencimento = datavencimento;
		this.parcela = parcela;
		this.dia = dia;
	}

	public Contasareceber(int unidade, Integer cliente, Date mesreferencia,
			String tipodoc, Integer venda, double valor, Date datavencimento,
			int parcela, int dia, Set parcelasarecebers) {
		this.unidade = unidade;
		this.cliente = cliente;
		this.mesreferencia = mesreferencia;
		this.tipodoc = tipodoc;
		this.venda = venda;
		this.valor = valor;
		this.datavencimento = datavencimento;
		this.parcela = parcela;
		this.dia = dia;
		this.parcelasarecebers = parcelasarecebers;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "codigo", unique = true, nullable = false)
	public Integer getCodigo() {
		return this.codigo;
	}

	public void setCodigo(Integer codigo) {
		this.codigo = codigo;
	}

	@Column(name = "unidade", nullable = false)
	public int getUnidade() {
		return this.unidade;
	}

	public void setUnidade(int unidade) {
		this.unidade = unidade;
	}

	@Column(name = "cliente")
	public Integer getCliente() {
		return this.cliente;
	}

	public void setCliente(Integer cliente) {
		this.cliente = cliente;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "mesreferencia", length = 10)
	public Date getMesreferencia() {
		return this.mesreferencia;
	}

	public void setMesreferencia(Date mesreferencia) {
		this.mesreferencia = mesreferencia;
	}

	@Column(name = "tipodoc", length = 20)
	public String getTipodoc() {
		return this.tipodoc;
	}

	public void setTipodoc(String tipodoc) {
		this.tipodoc = tipodoc;
	}

	@Column(name = "venda")
	public Integer getVenda() {
		return this.venda;
	}

	public void setVenda(Integer venda) {
		this.venda = venda;
	}

	@Column(name = "valor", nullable = false, precision = 13)
	public double getValor() {
		return this.valor;
	}

	public void setValor(double valor) {
		this.valor = valor;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "datavencimento", nullable = false, length = 10)
	public Date getDatavencimento() {
		return this.datavencimento;
	}

	public void setDatavencimento(Date datavencimento) {
		this.datavencimento = datavencimento;
	}

	@Column(name = "parcela", nullable = false)
	public int getParcela() {
		return this.parcela;
	}

	public void setParcela(int parcela) {
		this.parcela = parcela;
	}

	@Column(name = "dia", nullable = false)
	public int getDia() {
		return this.dia;
	}

	public void setDia(int dia) {
		this.dia = dia;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "contasareceber")
	public Set getParcelasarecebers() {
		return this.parcelasarecebers;
	}

	public void setParcelasarecebers(Set parcelasarecebers) {
		this.parcelasarecebers = parcelasarecebers;
	}

}
